server:
  port: 8080

spring:
  dubbo:
    application:
      id: lyw-server
      name: lyw-server
    registry:
      protocol: zookeeper
      address: 10.135.12.123:2181,10.135.12.124:2181,10.135.12.125:2181
    protocol:
      name: dubbo
      port: 20880
    provider:
      retries: 0
    consumer:
      timeout: 60000
      retries: 3
      check: true
    server: true
    scan: ltd.newbee.mall
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.138.26.200:3909/YLW_mall_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: sorcl_wz
      password: s23Ec1dSuk
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: ltd.newbee.mall.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
logging:
  config: classpath:log/log-config-dev.xml

kjt:
  payeeidentity: 200001725622
  privatekey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAKKHI0yprLceP6cvoxEuEM84DxHmEceaN5aMmiZrlAQE8RIBnsRpdV7ImffYgFS+KKBCKKue4GVSSuvLYI9EXV6S37TDreOKUFu9OHQrHu37oX2YiJHpYr+gyHaC64ZQlIQu1Uk4ti+2Tcnrg06bzat+sZTAH0l99pviR7VljOz7AgMBAAECgYBfBXtR2vGrrfexG1zPMouJW1EUOdqzRCqzzkhhpgvHvcvjpybX1oBUhhvel6mP4g2GhKeajyzKkC5VZXZyzJl5PF2DRFVMd5nZCsfsDNVk+/x0b1WjLjGJJrUJQBLPNxyUCws98sR3pN1DASDSr2690Vf/2+VMBsNcsJPbvMVxoQJBAOzkwEnqESqIVJVw2fRiNUAWBcOvVm3yCw/nz5SUitxF3T2mjQxBsif/aQmkk9hguUoxjFOBPIAhzz4ISed8BR8CQQCvouzEN6SkNX1iFmVYsfdJchOPZyBAGw5A+0VFHaleXgZTnbDviEcUx+zaQSjQ1QFiZtmMkqqW1jFXn4V3DmClAkEAp3PTkOwKElyoHbLV/m/lYFWw4XBx0eoEc8vS6h5OQgKIr2mpzn4p5ygeIZjagVtt3spDfUufbpt3mUvWofEC1QJBAJjui60bKlAVh1SmXZ7Kb6FTJHcEe891/4ZThHB3MGfMBUQ/lbYseoA8yR8OB6U3I9pz5dACUWm/nf1HGKafLUUCQQDo9dZD0PbEAkzKGP1UF5X3eOT+DlF/z8Wan7S9HoKMYlixbSHuReRbvnRDZuG/wbLBjt/0yE4bnnNFv65NN262
  kjtpublickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7phOZ9PHIivfzC6xzqJuF7935YG+j5LYnHnkex0I+Lw3oYOIKIESIrDMMbyNiBeezm3zh6Um+LzgGaaCzP0aV4bTFsS6RCveXFqG+dwHXE8e+YoxS4BTrjDzcZqDnbwNLsZz7wuSm6fSjV4YDL5zc2Ho1eV6OAzcITEfcBGxizaUmzP8s5bXqccWdPBOGVcoLOsvUugmNvmrhr1UL54LH0boZ5CAuOvCDaocBn/Fo7FNcomWnlG24Dynni/iGVTIS3DGU6fEY97JuSodZ4tCtnSnqzwksWaxy+7e+pv4ObFHSxAiTq3tVIaSFY5hJ9Dz3+Dm+RdF4LnyvZVIP3fcrQIDAQAB
  recv: https://zgateway.kjtpay.com/recv.do
  instantTradeAsyncNotify: http://10.190.176.150:8888/api/pay/instantTradeAsyncNotify
  transferToCardAsyncNotify: http://10.190.176.150:8888/api/pay/transferToCardAsyncNotify
  tradeRefundAsyncNotify: http://10.190.176.150:8888/api/pay/tradeRefundAsyncNotify
  transferToAccountAsyncNotify: http://10.190.176.150:8888/api/pay/transferToAccountAsyncNotify
  recvOrder: https://zmgs.kjtpay.com/mgs/recvOrder.htm
  verifyFlag: 0
  productCode: 10311

ftp:
  host: zsftp.kjtpay.com
  port: 5473
  username: 200001725622
  password: Pk43K6_yTj
  basePath: /opt/jsh/200001725622/photo