server:
  tomcat:
      uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30
  servlet:
    context-path: /
  connection-timeout: 5000ms

spring:
  profiles:
    active: dev

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.hailian.ylwmall.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
