package com.hailian.ylwmall.wsdl.supplier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-20T10:38:52.084+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW", name = "OuterSysVendorToMDM_NEW")
@XmlSeeAlso({ObjectFactory.class})
public interface OuterSysVendorToMDMNEW {

    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW", className = "com.hailian.ylwmall.wsdl.supplier.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW", className = "com.hailian.ylwmall.wsdl.supplier.ProcessResponse")
    public void process(

            @WebParam(name = "IN_VENDOR_CODE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inVENDORCODE,
            @WebParam(name = "IN_VENDOR_NAME", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inVENDORNAME,
            @WebParam(name = "IN_ACCOUNT_GRP_CODE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inACCOUNTGRPCODE,
            @WebParam(name = "IN_TAX_CODE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inTAXCODE,
            @WebParam(name = "IN_STREET_ROOM", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inSTREETROOM,
            @WebParam(name = "IN_POSTAL_CODE_CITY", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inPOSTALCODECITY,
            @WebParam(name = "IN_COUNTRY", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inCOUNTRY,
            @WebParam(name = "IN_REGION", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inREGION,
            @WebParam(name = "IN_PHONE_NUMBER", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inPHONENUMBER,
            @WebParam(name = "IN_SUB_COMPANY", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String inSUBCOMPANY,
            @WebParam(name = "T_VENDOR_COMPANY", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    HAIERMDMRSPVENDORCOMPANYTABLE tVENDORCOMPANY,
            @WebParam(name = "T_VENDOR_BANK", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    HAIERMDMRSPVENDORBANKTABLE tVENDORBANK,
            @WebParam(name = "T_VENDOR_PUR", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    HAIERMDMRSPVENDORPURTABLE tVENDORPUR,
            @WebParam(name = "T_VENDOR_FINA", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    HAIERMDMRSPVENDORFINANCETABLE tVENDORFINA,
            @WebParam(name = "T_VENDOR_BUNS", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    HAIERMDMRSPVENDORBUSINESSTABLE tVENDORBUNS,
            @WebParam(name = "SYSTEM_NAME", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String systemNAME,
            @WebParam(name = "VIEW_BANK", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String viewBANK,
            @WebParam(name = "VIEW_BASE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String viewBASE,
            @WebParam(name = "VIEW_COMP", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String viewCOMP,
            @WebParam(name = "VIEW_PUR", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String viewPUR,
            @WebParam(name = "VIEW_FINANCE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String viewFINANCE,
            @WebParam(name = "VIEW_BUSINESS", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String viewBUSINESS,
            @WebParam(name = "OPERATE_TYPE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String operateTYPE,
            @WebParam(name = "CREATED_BY", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String createdBY,
            @WebParam(name = "LEGAL_TYPE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String legalTYPE,
            @WebParam(name = "BILL_TYPE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    String billTYPE,
            @WebParam(mode = WebParam.Mode.OUT, name = "RETCODE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    javax.xml.ws.Holder<String> retcode,
            @WebParam(mode = WebParam.Mode.OUT, name = "RETMSG", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    javax.xml.ws.Holder<String> retmsg,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUT_ROW_ID", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    javax.xml.ws.Holder<String> outROWID,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUT_VENDOR_CODE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    javax.xml.ws.Holder<String> outVENDORCODE,
            @WebParam(mode = WebParam.Mode.OUT, name = "OUT_TAX_CODE", targetNamespace = "http://xmlns.oracle.com/Interface/OuterSysVendorToMDM_NEW/OuterSysVendorToMDM_NEW")
                    javax.xml.ws.Holder<String> outTAXCODE
    );
}
