
package com.hailian.ylwmall.wsdl.buyer;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.hailian.ylwmall.dto.ProfileDto;
import com.hailian.ylwmall.exception.BusinessException;
import lombok.extern.slf4j.Slf4j;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-19T09:50:18.967+08:00
 * Generated source version: 3.3.6
 *
 */
@Slf4j
public final class CreatePlCust2MDM_CreatePlCust2MDMPt_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM", "createplcust2mdm_client_ep");

    private CreatePlCust2MDM_CreatePlCust2MDMPt_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = Createplcust2MdmClientEp.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Createplcust2MdmClientEp ss = new Createplcust2MdmClientEp(wsdlURL, SERVICE_NAME);
        CreatePlCust2MDM port = ss.getCreatePlCust2MDMPt();

        {
        System.out.println("Invoking process...");
        // 基本信息
        String _process_inCUSTOMERNUMBER = "";
        String _process_inPARTNERFLAGSP = "1";
        String _process_inPARTNERFLAGSH = "1";
        String _process_inPARTNERFLAGBP = "1";
        String _process_inPARTNERFLAGPY = "1";

        String _process_inCUSTOMERTITLE = "公司";
        String _process_inACCOUNTGROUP = "0280";
        String _process_inCUSTOMERNAME = "test9010test239";
        String _process_inSEARCHTERMS = "TEST9010T";
        String _process_inCUSTOMERCOUNTRY = "CN";
        String _process_inLANGUAGE = "ZH";
        String _process_inREGION = "120";
        String _process_inCITY = "CN";
        String _process_inSTREET = "DFDSDFS";
        String _process_inCONTACTPERSON = "SDSDSA";
        String _process_inPHONENUMBER1 = "13223232323";
        String _process_inVATREGNO = "12147311";
        String _process_inINDUSTRYCLASS = "HY015";
        String _process_inTAXDOCTYPE = "02";
        String _process_inLEGALPERSON = "SDSADS";
        String _process_inLEGALTYPE = "01";
        String _process_inTRAINSTATION = "12A02";
        String _process_inTELEPHONE = "13212323232";

        //银行信息
        String _process_inBANKCOUNTRY = "CN";
        String _process_inBANKKEY = "102891500148"; //"105452000163";
        String _process_inACCOUNTHOLDER = "6217002390010212212";

        //公司信息
        String _process_inCOMPANYCODE = "1990";
        String _process_inRECONACCOUNT = "1122002000";
        String _process_inSORTKEY = "002";

        //销售信息
        String _process_inCUSTOMERSUMMARYGROUP = "1";
        String _process_inCURRENCY = "CNY";
        String _process_inCUSTOMERPRICEPROCEDURE = "1";
        String _process_inACCTASSGMTGROUP = "80";
        String _process_inTAXCLASSIFICATION = "1";
        String _process_inSHIPCONDITION = "01";
        String _process_inPODRELATION = "X";
        String _process_inSALESREGION = "370283001000";

        //快捷通信息
        String _process_inFINANACOUNTNAME = "1";
        String _process_inFINANORGN = "1";
        String _process_inFINANORGNSHORT = "KJT";
        String _process_inFINANACOUNTCODE = "1";
        String _process_inFINANCURRENCY = "CNY";
        String _process_inFINANTYPE = "2";
        String _process_inFINANSTATE = "0";

        // 公用字段
        String _process_inSYSNAME = "S01966";
        String _process_inCREATEDBY = "20010892";
        String _process_operatetype = "CREATE";
        String _process_updateBASE = "";
        String _process_updateBANK = "";
        String _process_updateEXTEND = "";
        String _process_updateSALE = "";
        String _process_updateCOMP = "";
        String _process_updateFINANCE = "";
        String _process_ifAFFIX = "";
        String _process_inAFFIXIP = "";
        String _process_inAFFIXUSERNAME = "";
        String _process_inAFFIXPASSWORD = "";
        String _process_inAFFIXURL = "";
        String _process_inAFFIXFILENAME = "";
        String _process_inADDRESSPROVINCE = "";
        String _process_inADDRESSCITY = "";
        String _process_inADDRESSAREA = "";
        String _process_inADDRESSTOWN = "";
        String _process_inADDRESSVILLAGE = "";
        String _process_inADDRESSROAD = "";
        String _process_inADDRESSHOUSENUMBER = "";
        String _process_inADDRESSLONGITUDE = "";
        String _process_inADDRESSLATITUDE = "";
        String _process_inSPECIFICADDRESS = "";
        String _process_inINNERCOMPANYCODE = "";
        javax.xml.ws.Holder<String> _process_outCUSTOMERCODE = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _process_retcode = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _process_retmsg = new javax.xml.ws.Holder<String>();
        port.process(_process_inCUSTOMERNUMBER, _process_inPARTNERFLAGSP, _process_inPARTNERFLAGSH, _process_inPARTNERFLAGBP, _process_inPARTNERFLAGPY, _process_inCUSTOMERTITLE, _process_inACCOUNTGROUP, _process_inCUSTOMERNAME, _process_inSEARCHTERMS, _process_inCUSTOMERCOUNTRY, _process_inLANGUAGE, _process_inREGION, _process_inCITY, _process_inSTREET, _process_inCONTACTPERSON, _process_inPHONENUMBER1, _process_inVATREGNO, _process_inINDUSTRYCLASS, _process_inTAXDOCTYPE, _process_inLEGALPERSON, _process_inLEGALTYPE, _process_inTRAINSTATION, _process_inTELEPHONE, _process_inBANKCOUNTRY, _process_inBANKKEY, _process_inACCOUNTHOLDER, _process_inCOMPANYCODE, _process_inRECONACCOUNT, _process_inSORTKEY, _process_inCUSTOMERSUMMARYGROUP, _process_inCURRENCY, _process_inCUSTOMERPRICEPROCEDURE, _process_inACCTASSGMTGROUP, _process_inTAXCLASSIFICATION, _process_inSHIPCONDITION, _process_inPODRELATION, _process_inSALESREGION, _process_inFINANACOUNTNAME, _process_inFINANORGN, _process_inFINANORGNSHORT, _process_inFINANACOUNTCODE, _process_inFINANCURRENCY, _process_inFINANTYPE, _process_inFINANSTATE, _process_inSYSNAME, _process_inCREATEDBY, _process_operatetype, _process_updateBASE, _process_updateBANK, _process_updateEXTEND, _process_updateSALE, _process_updateCOMP, _process_updateFINANCE, _process_ifAFFIX, _process_inAFFIXIP, _process_inAFFIXUSERNAME, _process_inAFFIXPASSWORD, _process_inAFFIXURL, _process_inAFFIXFILENAME, _process_inADDRESSPROVINCE, _process_inADDRESSCITY, _process_inADDRESSAREA, _process_inADDRESSTOWN, _process_inADDRESSVILLAGE, _process_inADDRESSROAD, _process_inADDRESSHOUSENUMBER, _process_inADDRESSLONGITUDE, _process_inADDRESSLATITUDE, _process_inSPECIFICADDRESS, _process_inINNERCOMPANYCODE, _process_outCUSTOMERCODE, _process_retcode, _process_retmsg);

        System.out.println("process._process_outCUSTOMERCODE=" + _process_outCUSTOMERCODE.value);
        System.out.println("process._process_retcode=" + _process_retcode.value);
        System.out.println("process._process_retmsg=" + _process_retmsg.value);

        }

        System.exit(0);
    }

    public static String callMdm(ProfileDto dto){
        URL wsdlURL = Createplcust2MdmClientEp.WSDL_LOCATION;
        Createplcust2MdmClientEp ss = new Createplcust2MdmClientEp(wsdlURL, SERVICE_NAME);
        CreatePlCust2MDM port = ss.getCreatePlCust2MDMPt();

        log.info("Invoking process...");
        // 基本信息
        String _process_inCUSTOMERNUMBER = "";
        String _process_inPARTNERFLAGSP = "1";
        String _process_inPARTNERFLAGSH = "1";
        String _process_inPARTNERFLAGBP = "1";
        String _process_inPARTNERFLAGPY = "1";

        String _process_inCUSTOMERTITLE = "公司";
        String _process_inACCOUNTGROUP = "0280";
        String _process_inCUSTOMERNAME = dto.getCompanyName();  // 客户名称
        String _process_inSEARCHTERMS = dto.getCompanyName().length() > 6 ? dto.getCompanyName().substring(0, 6) : dto.getCompanyName(); //最好限制在6个字符内，SAP有限制
        String _process_inCUSTOMERCOUNTRY = "CN";
        String _process_inLANGUAGE = "ZH";
        String _process_inREGION = ""; // dto.getProvince();
        String _process_inCITY = dto.getCity();
        String _process_inSTREET = dto.getArea();
        String _process_inCONTACTPERSON = dto.getContactor();
        String _process_inPHONENUMBER1 = dto.getContactorPhone();
        String _process_inVATREGNO = dto.getTaxNo(); // 增值税号 "121471919"
        String _process_inINDUSTRYCLASS = "HY007";
        String _process_inTAXDOCTYPE = dto.getTaxType();
        String _process_inLEGALPERSON = "";
        String _process_inLEGALTYPE = "01";
        String _process_inTRAINSTATION = "";
        String _process_inTELEPHONE = dto.getContactorPhone();

        //银行信息
        String _process_inBANKCOUNTRY = "CN";
        String _process_inBANKKEY = dto.getBankCode(); //"105452000163";
        String _process_inACCOUNTHOLDER = dto.getBankAccNo(); //"6217002390010212212"

        //公司信息
        String _process_inCOMPANYCODE = "1990";
        String _process_inRECONACCOUNT = "1122002000";
        String _process_inSORTKEY = "002";

        //销售信息
        String _process_inCUSTOMERSUMMARYGROUP = "1";
        String _process_inCURRENCY = "CNY";
        String _process_inCUSTOMERPRICEPROCEDURE = "1";
        String _process_inACCTASSGMTGROUP = "20";
        String _process_inTAXCLASSIFICATION = "1";
        String _process_inSHIPCONDITION = "01";
        String _process_inPODRELATION = "";
        String _process_inSALESREGION = "";

        //快捷通信息
        String _process_inFINANACOUNTNAME = "";
        String _process_inFINANORGN = "";
        String _process_inFINANORGNSHORT = "";
        String _process_inFINANACOUNTCODE = "";
        String _process_inFINANCURRENCY = "";
        String _process_inFINANTYPE = "";
        String _process_inFINANSTATE = "";

        // 公用字段
        String _process_inSYSNAME = "S01966";
        String _process_inCREATEDBY = "20010892";
        String _process_operatetype = "CREATE";
        String _process_updateBASE = "";
        String _process_updateBANK = "";
        String _process_updateEXTEND = "";
        String _process_updateSALE = "";
        String _process_updateCOMP = "";
        String _process_updateFINANCE = "";
        String _process_ifAFFIX = "";
        String _process_inAFFIXIP = "";
        String _process_inAFFIXUSERNAME = "";
        String _process_inAFFIXPASSWORD = "";
        String _process_inAFFIXURL = "";
        String _process_inAFFIXFILENAME = "";
        String _process_inADDRESSPROVINCE = "";
        String _process_inADDRESSCITY = "";
        String _process_inADDRESSAREA = "";
        String _process_inADDRESSTOWN = "";
        String _process_inADDRESSVILLAGE = "";
        String _process_inADDRESSROAD = "";
        String _process_inADDRESSHOUSENUMBER = "";
        String _process_inADDRESSLONGITUDE = "";
        String _process_inADDRESSLATITUDE = "";
        String _process_inSPECIFICADDRESS = "";
        String _process_inINNERCOMPANYCODE = "";
        javax.xml.ws.Holder<String> _process_outCUSTOMERCODE = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _process_retcode = new javax.xml.ws.Holder<String>();
        javax.xml.ws.Holder<String> _process_retmsg = new javax.xml.ws.Holder<String>();
        port.process(_process_inCUSTOMERNUMBER, _process_inPARTNERFLAGSP, _process_inPARTNERFLAGSH, _process_inPARTNERFLAGBP, _process_inPARTNERFLAGPY, _process_inCUSTOMERTITLE, _process_inACCOUNTGROUP, _process_inCUSTOMERNAME, _process_inSEARCHTERMS, _process_inCUSTOMERCOUNTRY, _process_inLANGUAGE, _process_inREGION, _process_inCITY, _process_inSTREET, _process_inCONTACTPERSON, _process_inPHONENUMBER1, _process_inVATREGNO, _process_inINDUSTRYCLASS, _process_inTAXDOCTYPE, _process_inLEGALPERSON, _process_inLEGALTYPE, _process_inTRAINSTATION, _process_inTELEPHONE, _process_inBANKCOUNTRY, _process_inBANKKEY, _process_inACCOUNTHOLDER, _process_inCOMPANYCODE, _process_inRECONACCOUNT, _process_inSORTKEY, _process_inCUSTOMERSUMMARYGROUP, _process_inCURRENCY, _process_inCUSTOMERPRICEPROCEDURE, _process_inACCTASSGMTGROUP, _process_inTAXCLASSIFICATION, _process_inSHIPCONDITION, _process_inPODRELATION, _process_inSALESREGION, _process_inFINANACOUNTNAME, _process_inFINANORGN, _process_inFINANORGNSHORT, _process_inFINANACOUNTCODE, _process_inFINANCURRENCY, _process_inFINANTYPE, _process_inFINANSTATE, _process_inSYSNAME, _process_inCREATEDBY, _process_operatetype, _process_updateBASE, _process_updateBANK, _process_updateEXTEND, _process_updateSALE, _process_updateCOMP, _process_updateFINANCE, _process_ifAFFIX, _process_inAFFIXIP, _process_inAFFIXUSERNAME, _process_inAFFIXPASSWORD, _process_inAFFIXURL, _process_inAFFIXFILENAME, _process_inADDRESSPROVINCE, _process_inADDRESSCITY, _process_inADDRESSAREA, _process_inADDRESSTOWN, _process_inADDRESSVILLAGE, _process_inADDRESSROAD, _process_inADDRESSHOUSENUMBER, _process_inADDRESSLONGITUDE, _process_inADDRESSLATITUDE, _process_inSPECIFICADDRESS, _process_inINNERCOMPANYCODE, _process_outCUSTOMERCODE, _process_retcode, _process_retmsg);

        log.info("process._process_outCUSTOMERCODE=" + _process_outCUSTOMERCODE.value);
        log.info("process._process_retcode=" + _process_retcode.value);
        log.info("process._process_retmsg=" + _process_retmsg.value);
        if("S".equalsIgnoreCase(_process_retcode.value)){
            return _process_outCUSTOMERCODE.value;
        }else{
            log.error("调用mdm未成功: " + _process_retmsg.value);
            throw new BusinessException("调用mdm未成功: ", _process_retmsg.value);
        }

    }

}
