package com.hailian.ylwmall.wsdl.buyer;

import com.hailian.ylwmall.common.SpringContextUtils;
import com.hailian.ylwmall.config.WSDLConfig;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-19T09:50:19.092+08:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "createplcust2mdm_client_ep",
                  wsdlLocation = "",
                  targetNamespace = "http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM")
public class Createplcust2MdmClientEp extends Service {
    static String wsdlUrl = SpringContextUtils.getBean(WSDLConfig.class).getCustomerWSDL();

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM", "createplcust2mdm_client_ep");
    public final static QName CreatePlCust2MDMPt = new QName("http://xmlns.oracle.com/interface_new/CreatePlCust2MDM/CreatePlCust2MDM", "CreatePlCust2MDM_pt");
    static {
        URL url = null;
        try {
            url = new URL(wsdlUrl);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Createplcust2MdmClientEp.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", wsdlUrl);
        }
        WSDL_LOCATION = url;
    }

    public Createplcust2MdmClientEp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Createplcust2MdmClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Createplcust2MdmClientEp() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Createplcust2MdmClientEp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Createplcust2MdmClientEp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Createplcust2MdmClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CreatePlCust2MDM
     */
    @WebEndpoint(name = "CreatePlCust2MDM_pt")
    public CreatePlCust2MDM getCreatePlCust2MDMPt() {
        return super.getPort(CreatePlCust2MDMPt, CreatePlCust2MDM.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreatePlCust2MDM
     */
    @WebEndpoint(name = "CreatePlCust2MDM_pt")
    public CreatePlCust2MDM getCreatePlCust2MDMPt(WebServiceFeature... features) {
        return super.getPort(CreatePlCust2MDMPt, CreatePlCust2MDM.class, features);
    }

}
